### ISSUE TITLE
Context seems to have changed for @webpack-blocks/dev-server2

### ISSUE THREAD

**Issue by joefraley** [andywer/webpack-blocks#105]
Using webpack2 and webpack-dev-server2. Having a build time error while using webpack-devserver-2 block.

See [this gist](https://gist.github.com/joefraley/57bd6ac36d9bd630dbaf55898f5ad656) for a minimal reproducible example.
You can also [clone this repo](https://github.com/joefraley/webpack-block-error), `npm install`, `npm start`

Error here:
```bash
/Users/.../example-webpack/node_modules/@webpack-blocks/webpack-common/lib/devServer.js:58
    plugins: [new context.webpack.HotModuleReplacementPlugin()]
                                 ^
TypeError: Cannot read property 'HotModuleReplacementPlugin' of undefined
    at postConfig (/Users/fraleyj/example-webpack/node_modules/@webpack-blocks/webpack-common/lib/devServer.js:58:34)
    at /Users/fraleyj/example-webpack/node_modules/@webpack-blocks/core/lib/index.js:116:25
    at Array.reduce (native)
    at invokeConfigSetters (/Users/fraleyj/example-webpack/node_modules/@webpack-blocks/core/lib/index.js:115:24)
    at invokePostHooks (/Users/fraleyj/example-webpack/node_modules/@webpack-blocks/core/lib/index.js:130:10)
    at Object.createConfig (/Users/fraleyj/example-webpack/node_modules/@webpack-blocks/core/lib/index.js:40:29)
    at createConfig (/Users/fraleyj/example-webpack/node_modules/@webpack-blocks/webpack2/index.js:58:15)
    at Object.<anonymous> (/Users/fraleyj/example-webpack/webpack.config.js:9:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

I don't understand why, but it looks like [this use of `context`](https://github.com/andywer/webpack-blocks/blame/master/packages/webpack-common/src/devServer.js#L52) is mixed up somehow:

```javascript
function postConfig (context, config) {
  const entryPointsToAdd = context.devServer.entry.length > 0
    ? context.devServer.entry
    : [ 'webpack/hot/only-dev-server' ]
  // console.log(context) <---- this has HotModuleReplacementPlugin on it, does not have webpack.HotModuleReplacementPlugin
  return {
    devServer: Object.assign({
      hot: true,
      historyApiFallback: true,
      inline: true
    }, context.devServer.options),
    entry: addDevEntryToAll(config.entry || {}, entryPointsToAdd),
    plugins: [
      new context.webpack.HotModuleReplacementPlugin() // <--- context.webpack === undefined
    ]
  }
}
```

The issue seems to be introduced by [this PR](https://github.com/andywer/webpack-blocks/commit/f7b20afbd34321ce38daaf4a6cc37604191bbf7c#diff-d026851978a5b2bbc7069d4901282b78R45).

I can open a PR with the fix, but I don't understand the assumptions here or how `context` is intended to work, such that the above PR might've been confused.

**Comment by joefraley** [comment]
Seems to be related to my version choice:
```json
    "@webpack-blocks/dev-server2": "0.4.0-rc",
    "@webpack-blocks/webpack2": "0.4.0-rc.2",
```

not sure why i chose to use those, but, 

```json
    "@webpack-blocks/dev-server2": "0.4.0",
    "@webpack-blocks/webpack2": "0.4.0",
```

does not have the same problem

**Comment by andywer** [comment]
Hey @joefraley. Thanks for your report!

Yeah, I was already typing exactly that when your latest comment appeared on my screen... 😉

I cannot tell you the exact reason why so far, but I am pretty sure it is due to the changed function signature of `createConfig()` in `@webpack-blocks/core`. I guess the dependency version ranges were not strict in the RC versions...

**Comment by andywer** [comment]
The gist and the repo were great to debug the issue, though 👍

Can we close this issue? I tried and it installed the `0.4.0` by default. You probably copied the version from another project where you ran the `npm i --save-dev` last Friday or earlier, before the final `0.4.0` was published.

**Comment by joefraley** [comment]
Totally, sounds great. Thanks @andywer
