### ISSUE TITLE
Example of using sass ?

### ISSUE THREAD

**Issue by ngduc** [andywer/webpack-blocks#107]
Hi,
I tried to use sass, imported .scss files but it gives some build errors (loader is needed for this format, etc.).
Do you have an example for using sass?
Thanks.

**Comment by andywer** [comment]
Hi @ngduc.

The minimal example in the sass block's [README](https://www.npmjs.com/package/@webpack-blocks/sass) should work.

If not, please share the error message, the node version you are using and preferrably a link to your source files (esp. the `webpack.config.js` and the `package.json`) :)

**Comment by ngduc** [comment]
It works now. Thank you @andywer .
