### ISSUE TITLE
Warn if first argument in createConfig is not of type array

### ISSUE THREAD

**Issue by TimonVS** [andywer/webpack-blocks#110]
I made the mistake to not put the config in an array, the result was that I wasted at least half an hour debugging the result of `createConfig`. It'd be nice for DX to add a warning for this :).

I do wonder why `createConfig` expects an array though, because it seems that there's only one argument, so wouldn't it be better to just spread the arguments or use the `arguments` variable (if older version of Node should be supported)?

**Comment by andywer** [comment]
Hey @TimonVS.

Good point. Improvements in DX are always welcome! :)

The array/spread thing is not new, though. There was already an issue for that and a poll on twitter. See #38 😉
