### ISSUE TITLE
Any plans to create a LESS plugin?

### ISSUE THREAD

**Issue by kirill-konshin** [andywer/webpack-blocks#113]
Currently only SASS is supported, any plans to also support LESS?

**Comment by andywer** [comment]
I think @Veikedo already wrote one (see #80). Maybe he would like to open a PR for it?

If not: It's not hard. Sharing would definitely be nice, though :)

**Comment by Veikedo** [comment]
Actually I don't have a separated block for less. I have only this config
![image](https://cloud.githubusercontent.com/assets/5779339/22958738/cc01ef58-f363-11e6-999c-7c76fb469d1b.png)

But I think it's we can just copy the `sass` block and modify it a bit
```

/**
 * @param {object}   [options]                  See http://lesscss.org/usage/#command-line-usage-options
 */
function less(options) {
    "use strict";

    options = options || {};

    const hasOptions = Object.keys(options).length > 0;

    return (context) => ({
        module: {
            loaders: [
                {
                    test: context.fileType('text/x-less'),
                    loaders: [
                        'style-loader',
                        options.sourceMap ? 'css-loader?sourceMap' : 'css-loader',
                        hasOptions ? 'less-loader?' + JSON.stringify(options) : 'less-loader'
                    ]
                }
            ]
        }
    });
}


```

**Comment by Veikedo** [comment]
will open a PR soon

**Comment by vlad-zhukov** [comment]
The Less block has been released as a community block: https://github.com/kirill-konshin/webpack-blocks-less
