### ISSUE TITLE
SASS block + ExtractText2 block

### ISSUE THREAD

**Issue by kirill-konshin** [andywer/webpack-blocks#115]
SASS block does not work with ExtractText2 block, produced output has all styles in the bundle as a CSS string, e.g. not extracted as they should be.

**Comment by jvanbruegge** [comment]
you have to add the second argument to the block, the mime type, in this case `text/x-sass`

**Comment by andywer** [comment]
I think the documentation of the `sass` and the `extract-text` block should be improved to make the usage clearer.

**Comment by kirill-konshin** [comment]
Yep, it worked with extra option. 

Important remark: when `extractText` is before `sass` it produces an error: `Error: text/x-sass loader could not be found in webpack config`:

module.exports = createConfig([
    extractText('css/[name].css', 'text/x-sass'),
    sass({relative_assets: true})
]);
