### ISSUE TITLE
Cannot use extractText block to produce html files

### ISSUE THREAD

**Issue by jsonnull** [andywer/webpack-blocks#117]
I'm trying to use the extractText block to produce html files alongside a bundle.

When I attempt to do so, I get the error
```
Expected "style-loader" to be first loader of .css files. Instead got: html-loader
```

I'm not sure if this is a sanity check which is meant to be helpful, or if usage of extractText is coupled to style-loader internally.

Can this restriction be lifted?

The only way around this I can see is to avoid using extractText entirely and extend a custom block to include the plugin.

**Comment by andywer** [comment]
Good point. Thanks for reporting, @jsonnull!

Yeah, it is supposed to be the `extract-text` block, not just `extract-styles` 😉

**Comment by andywer** [comment]
@jsonnull Sorry for the delay, but I am now on it!

Already fixed it, in fact. Just need to write a regression test. Tell me if you would like to try the fixed version before I officially publish it :)

**Comment by jsonnull** [comment]
@andywer Awesome, I'm happy to try it! Can you link me to the branch/commit it's on?

**Comment by andywer** [comment]
Try `extract-text`/`extract-text2` in version `0.4.1-beta` 😉

Code is here: https://github.com/andywer/webpack-blocks/tree/bugfix/extract-text-for-non-style-assets

**Comment by andywer** [comment]
Hey @jsonnull. Did you try it? The issue's been open for ages 😉

**Comment by andywer** [comment]
Ping.

**Comment by andywer** [comment]
Closing it for now. Feel free to re-open if issue is still a thing in webpack-blocks 1.0
