### ISSUE TITLE
Allow extract-text to aggregate multiple content types at once (CSS & SASS)

### ISSUE THREAD

**Issue by iBelieve** [andywer/webpack-blocks#139]
It looks like the extract-text2 block only accepts one file type, and using the block twice results in two different CSS files. It would be nice if I could extract both my SCSS and CSS files into one CSS file.

**Comment by andywer** [comment]
Hey @iBelieve. Thanks for the feedback!

You are right, currently that's not possible. The extract-text block would need to work with an array of file types and it would work just fine, I think.

I took the liberty to adjust the title in order to make the requested feature a little clearer.

**Comment by sapegin** [comment]
@andywer Could you clarify what should we do here? API example?

**Comment by andywer** [comment]
Might already be solved by `match()`.

@iBelieve Is that still an issue? Have you tried using the 1.0 beta with [match()](https://github.com/andywer/webpack-blocks/releases/tag/v1.0.0-beta) yet?

**Comment by andywer** [comment]
Seems outdated. Closing.
