### ISSUE TITLE
Sass Modules

### ISSUE THREAD

**Issue by pakokrew** [andywer/webpack-blocks#142]
Webpack blocks allow to use both global **SASS** and **CSS** modules, but we cannot use **SASS modules**.

We should either create a `sassModule` block, or add to `cssModule` the ability to load `x-sass` files and add `sass-loader`

I managed to use sass modules by merging css modules and sass configs :
```
{
    module:
      {
        loaders: [
          {
            test: context.fileType('text/x-sass'),
            loaders: [
              'style-loader',
              'css-loader?importLoaders=1&localIdentName=[name]--[local]--[hash:base64:5]&modules',
              'sass-loader',
            ]
          }
        ]
      }
  }
 ```

**Comment by andywer** [comment]
Hey @pakokrew!

Good point, but not sure yet if it justifies a new block. Maybe it's fine just to add a second parameter to the `sass` block to pass `css-loader` options?

**Comment by jvanbruegge** [comment]
This is basicly the same problem as #115 
Those blocks should both have a post hook doing that themself

**Comment by andywer** [comment]
@jvanbruegge I don't think it's a similar issue, at least not the way it works right now. 115 is about moving it to a post hook, as you wrote, but here the post hook would not make a difference, since the `sass` block ships a separate `css-loader` instance for the *.sass/*.scss files we want to configure.

**Comment by jvanbruegge** [comment]
But you pipe the result into a css loader: https://github.com/andywer/webpack-blocks/blob/master/packages/sass/index.js#L29
A post hook could add tge needed query string

**Comment by andywer** [comment]
But why the post hook? We could leave it as it is and just add an options parameter for the css-loader option. Shouldn't make much difference, except that it's simpler. Or maybe I am missing something 😉

(Wouldn't add a post hook to the block unless it adds some real value)

**Comment by jvanbruegge** [comment]
I mean a post hook on the css-modules block. So it can check all loaders for `css-loader` entries and add the query string there. So it _just works_ when using css-modules with sass or less

**Comment by andywer** [comment]
Ahhh, now we are on the same page :)

Interesting thought, but we also have to consider that the user might not want to change *all* css-loaders. Even without the sass block you might want to load local css files as modules and css files from `node_modules/` as plain old css, for instance.

**Comment by pakokrew** [comment]
I think we reach the point where the configuration is too specific to use cases, which maybe webpack blocks is not here to answer that but just helping "common" uses cases ...

**Comment by andywer** [comment]
I agree. We should pay attention not to overengineer the blocks. If people have very specific / unusal requirements they can still write their own custom blocks.

**Comment by andywer** [comment]
But being able to customize the css-loader's options for the `sass` use case should still be supported in some way, I think. Adding another parameter to the sass blocks seems to be a simple solution.

@jvanbruegge's point is also valid, but might lead to a more complicated solution if I am right?

**Comment by jvanbruegge** [comment]
Well more compilcated than an option, but not really.
you just map over the rules, and if it contains the css-loader, then add the query string.
You could even add an optional array with mimetypes and/or exclude regexes to skip

**Comment by andywer** [comment]
I just fear that applying to all css-loaders by default and excluding certain ones can easily get tricky / can run into edge-cases.

As I think about it... The thing that scares me about it (🙈😅) is that we would have to modify module rules that have already been set by other blocks. I like to keep the data is immutable as possible, because otherwise when debugging you might have a hard time figuring out which block was actually responsible for the faulty config. If it's immutable it's easy: The block that created it 😉

**Comment by andywer** [comment]
I hope the new [match()](https://github.com/andywer/webpack-blocks/issues/125#issuecomment-302942761) will fix this as well... :)

**Comment by protoEvangelion** [comment]
@andywer Could you please provide an example of how to use match() with sass modules? Your PR looks great, but I couldn't figure out how to use it.

**Comment by andywer** [comment]
Hey @protoEvangelion. Try:

```js
match('*.scss', [
  css.modules(),
  sass()
])
```

But your are completely right, there should be a section in the `sass` block README describing that! Will open a PR for that :)

PS: Tell me if the snippet works for you 😉

**Comment by protoEvangelion** [comment]
Hey @andywer thanks for your quick response!  Please forgive my ignorance, but I can't seem to get it to work.

Should I be pulling `match` out of the `@webpack-blocks/webpack2` package?

***And should I be referencing css modules like this?***

```js
const { match } = require('@webpack-blocks/webpack2')
const cssModules = require('@webpack-blocks/css-modules')

match('*.scss', [
    cssModules(),
    sass()
  ]),
  css(),
```

**Comment by andywer** [comment]
Just use the new `webpack-blocks` package :)

Like this:

```js
const { createConfig, css, match } = require('webpack-blocks')

module.exports = createConfig([
  match('*.scss', [
    css.modules(),
    sass()
  ])
])
```

**Comment by andywer** [comment]
Also be aware that `match()` is a 1.0 feature and there is no more `webpack-blocks/webpack2` in 1.0. There is only `webpack-blocks/webpack` in 1.0 which targets webpack 2+.

But it makes sense just to stick to the new convenience `webpack-blocks` package that wraps all the most common packages 😉

**Comment by protoEvangelion** [comment]
@andywer Thanks for the explanation :)

I've tried a bunch of things however it is still not working.  Here is what I currently have:

```js
const { createConfig, css, sass, match } = require('webpack-blocks')

module.exports = createConfig([
  match('*.scss', [
    css.modules(),
    sass()
  ]),
 css()
])

```

Does that all look kosher to you?

Here is the error in my console: `Error: Expected a function, instead got a object. Beware that the block API changed since version 0.x.`

**Comment by andywer** [comment]
@protoEvangelion Check out the pull request #172. It adds an end-to-end test for this particular use case. The snippet you sent seems correct, but incomplete. Compare to the PR.

If it really doesn't work, feel free to put a minimal non-working SASS + CSS modules setup on GitHub and link to it here. Sorry for the troubles, it should be pretty straight-forward to make that work 😉

**Comment by andywer** [comment]
Closing that, since I think that has been fixed. Feel free to re-open if I am wrong.

**Comment by protoEvangelion** [comment]
It's good to go!  Thanks for all you do @andywer

**Comment by Jack-Barry** [comment]
If anyone else is interested in using Sass with CSS modules, this is what I came up with which is working pretty nicely:

```js
const {
  createConfig,
  entryPoint,
  setOutput,
  match,
  addPlugins,
  extractText,
  env,
  
  babel,
  css,
  sass,
  
  webpack
} = require('webpack-blocks');

const HtmlWebpackPlugin = require('html-webpack-plugin');
const cssPatterns       = ['*.scss', '*.css'];
const cssLoaders        = [css.modules({localIdentName: '[name]__[local]___[hash:base64:5]'}), sass()];
const cssLoadersProd    = cssLoaders.concat([extractText('styles.css')]);

module.exports = createConfig([
  entryPoint('./app/index.js'),
  setOutput('./dist/bundle.js'),
  babel(),
  addPlugins([
    new HtmlWebpackPlugin({
      template: './app/index.html',
      filename: 'index.html',
      inject:   'body'
    })
  ]),
  env('development', [
    match(
      cssPatterns,
      cssLoaders
    )
  ]),
  env('production', [
    match(
      cssPatterns,
      cssLoadersProd
    )
  ])
]);
```
