### ISSUE TITLE
How to set output name for file-loader?

### ISSUE THREAD

**Issue by marcofugaro** [andywer/webpack-blocks#145]
Sorry if this is not really an issue, but I had problems setting a custom output name for my assets, I want to use the formula that `create-react-app` uses which is `[name].[hash:8].[ext]`, instead of the default long hash. [Here is the code where it's used.](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L152)

I didn't find a simpler way than replacing all the file-loader itself, or does object merging works there?

**Comment by andywer** [comment]
I think that's not possible right now, unless you want to monkeypatch the config as a post-processing step. Should be possible when 1.0 is ready and you have to explicitly include asset loaders (we can make them accept options like this then).

(Will close the issue right away unless you've got further related questions :) )

**Comment by marcofugaro** [comment]
Thanks for the explaination and for your time! Yes, can't wait for v1.0!
