### ISSUE TITLE
@webpack-blocks/sass Allow using indentedSyntax

### ISSUE THREAD

**Issue by Kadrian** [andywer/webpack-blocks#15]
*Problem*
When I want to write `.sass` files instead of `.scss`, there should be a way to pass query params to the sass loader like `sass?indentedSyntax`, right?

Any thoughts how to make this configurable?

**Comment by andywer** [comment]
Hey @Kadrian! Good point, thank you.

Fortunately, this is pretty easy. We just have to add an options parameter to the `sass` block and pass it to the `sass-loader`: https://github.com/andywer/webpack-blocks/blob/master/packages/sass/index.js

https://github.com/andywer/webpack-blocks/blob/master/packages/css-modules/index.js already does it like that, for example.

Depending on how urgent this is you can wait for me to fit it or try it yourself and open a PR :)

(SASS loader's options = node-sass' options: https://github.com/sass/node-sass#options)

**Comment by andywer** [comment]
Suggestion of which options to pass to the `sass-loader` for now:
- includePaths
- indentedSyntax
- outputStyle
- sourceMap (also add to `css-loader`)

**Comment by andywer** [comment]
@Kadrian PR is open. I already published it as `@webpack-blocks/sass@0.1.2-beta`, so you can test it locally :)

Would be great if you could test it for your use case and confirm it does it's job.

**Comment by andywer** [comment]
@Kadrian Just noticed that current `sass-loader`/`node-sass` versions seem to allow indent syntax without setting the option 👍
