### ISSUE TITLE
resolveModules

### ISSUE THREAD

**Issue by diegohaz** [andywer/webpack-blocks#152]
I'm currently using this snippet on my code: https://github.com/diegohaz/arc/blob/c066d6d0039fa5d782e8e3691f9d2bf3530a05bf/webpack.config.js#L36-L40

Since we have `resolveAliases` here, I wonder if it would be good to have a `resolveModules` block as well.

I can send a PR.

**Comment by andywer** [comment]
Hey @diegohaz.

Yeah, might make sense to have a `resolveModules` in `@webpack-blocks/webpack`.

Or: Maybe just provide a `resolve()` to be used like `resolve({ modules: [ 'node_modules' ] })` or `resolve({ alias: { react: 'preact-compat' } })`?

@jvanbruegge

**Comment by andywer** [comment]
@jvanbruegge What do you think?

**Comment by jvanbruegge** [comment]
Sorry, somehow I missed the first notification.
I would say 👍 , and I would make `resolve` not `resolveModules`

**Comment by BooleT37** [comment]
Some documentation would be nice
