### ISSUE TITLE
Code review request: webpack-blocks-copy

### ISSUE THREAD

**Issue by bkonkle** [andywer/webpack-blocks#161]
Hi! I've got `webpack-blocks-copy` cleaned up a bit and updated for 1.0. I'd love some quick code review on the `develop` branch when someone gets a chance. :-)

https://github.com/ecliptic/webpack-blocks-copy

If all looks good, I'll move over my other blocks the same way. 👍 

Thanks!

**Comment by jvanbruegge** [comment]
Why do you need a whole block for just one plugin?
I use the copy plugin by simply putting: `addPlugin([new CopyWebpackPlugin(from, to)])` in my config.

**Comment by bkonkle** [comment]
Mainly the convenience of accumulating multiple copy calls depending on the environment. Each call to `copy()` adds a new pattern to the stack, and the actual plugin isn't instantiated until the end with the final config.

**Comment by bkonkle** [comment]
I _could_ add it to `webpack-blocks-utils`, but then that would introduce `CopyWebpackPlugin` as a dependency whether people are using it or not. I was trying to avoid that, but maybe it's not a big deal?

**Comment by andywer** [comment]
Hey @bkonkle :)

Since we are strictly talking dev dependencies here and I assume the `CopyWebpackPlugin` dependency is not that big (= does not add much overhead) I'd say that adding it to `webpack-blocks-utils` is probably fine.

The code looks fine to me. With the flow types you are already ahead of us... ^^

**Comment by bkonkle** [comment]
Cool - I'll merge it into `webpack-blocks-utils` and update that package as well. Thanks for the feedback!
