### ISSUE TITLE
Remove `node-sass` from dependencies, update `sass-loader`

### ISSUE THREAD

**Issue by bkonkle** [andywer/webpack-blocks#164]
Looks like we need to bump `node-sass` to support Node 8: https://github.com/sass/node-sass/issues/1984

I tried to test out the change, but I don't see anywhere that `node-sass` is actually being used. Is it there just because of the peer dependency in `sass-loader`?

In any case, for Node 8 support we'll need to bump them to the latest versions. :-)

**Comment by andywer** [comment]
Thanks for pointing out, @bkonkle!

Yes, I think `node-sass` was a peer dependency of the `sass-loader`. Will create a PR.
