### ISSUE TITLE
Webpack-blocks-dev-server

### ISSUE THREAD

**Issue by Geczy** [andywer/webpack-blocks#179]
https://github.com/andywer/webpack-blocks/blob/release/1.0/packages/dev-server/package.json#L22

Please update to latest dev-server

``` 
"webpack-dev-middleware@1.10.2" has incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
```

**Comment by sapegin** [comment]
Feel free to send a pull request ;-)
