### ISSUE TITLE
Add dependencies / devDependencies on blocks

### ISSUE THREAD

**Issue by eXon** [andywer/webpack-blocks#19]
It would be great if it was possible to automatically install the dependencies / devDependencies needed when using a block.

That way, you don't need to know when using @webpack-block/typescript which typescript loader you need to use with it.

Is there a way to achieve something like that ATM?

**Comment by andywer** [comment]
Which node version are you using? Node 5+ should flatten the `node_modules`, so you could just rely on the transitive dependency. It's really not best practice, but you could give it a try.

A clean solution could be achieved when there is a CLI tool (👉 #7).

**Comment by eXon** [comment]
I'm on Node 6 but by doing that, you choose the library version for the user instead of letting him choose to update them. Not sure how this is handled honestly.

For the CLI, I think [create-react-app](https://github.com/facebookincubator/create-react-app) pretty much nailed that. It's worth a look.

**Comment by andywer** [comment]
Right, you wouldn't care about webpack plugin/loader versions anymore at all. But from a pragmatic point of view: Do you really care which loader versions you use? I guess most people just set them up once and never touch them again...

I know create-react-app. The CLI I have in mind aims for something else:
1. What if you need a webpack setup, but no react?
2. CRA is really cool to get going fast and easy, but if you need to change the webpack config you run the *eject* script and you are left pretty much alone with the webpack hazzle it successfully hid from you before.

Should probably add this to the other issue... But we are losing focus here 😉

**Comment by eXon** [comment]
Closing this I'll let the discussion continue on the correct issue.
