### ISSUE TITLE
Update extract-text-webpack-plugin

### ISSUE THREAD

**Issue by sapegin** [andywer/webpack-blocks#190]
When using webpack 3 I have a warning:

```
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was installed.
```

The problem is the new extract-text-webpack-plugin has [some breaking changes](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v3.0.0) and requires webpack 3.1. Which means if we update it webpack-blocks packages would require webpack 3.1 too.

**Comment by andywer** [comment]
But extract-text-plugin v2 works with webpack v3, right?

**Comment by jvanbruegge** [comment]
But it throws a deprecation warning

**Comment by andywer** [comment]
I just want to make sure it actually works, because of a [comment in the extract-text-plugin issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/567#issuecomment-322868345).

**Comment by d3viant0ne** [comment]
@andywer - It's not compatible with 2.x. Outside of the deprecations where it's breaking mentioned in the linked issue, css is extracted in the wrong order in certain cases. So while is works for some, Angular for instance, it does not work for everyone.

**Comment by andywer** [comment]
Thx for clarifying, @d3viant0ne :)

**Comment by d3viant0ne** [comment]
I'd love to tell you there is something we can do here but etwp happens to be the one lib where we in contrib have little to no control given how tightly coupled it is to Webpack.

Only real silver lining I can give you is that it's functionality will be migrated into Webpack where it belongs which should save everyone, myself included quite a bit of pain.

**Comment by sapegin** [comment]
@d3viant0ne Tell us whether people still use webpack 2?

I would just drop webpack 2 support and update extract-text-webpack-plugin to the latest version ;-)

**Comment by d3viant0ne** [comment]
@sapegin - iirc the npm API doesn't have statistics on specific versions of packages ( revenue opportunity for npm? ).

As you can imagine & given from previous Majors, there is always a group of applications that is at least one Major behind. I'll see if I can come up with a set of numbers with Sean that is at least moderately accurate.
