### ISSUE TITLE
Rename babel6 to babel before 1.0 release

### ISSUE THREAD

**Issue by sapegin** [andywer/webpack-blocks#191]
`babel6` is the only block that has a version number in its name, and Babel 7 is in alpha.

**Comment by andywer** [comment]
Don't have strong feelings about that. My initial thought was to allow the user to choose which babel major version to use, since in the past they tended to be pretty breaking.

For babel 6 => babel 7 I don't see big breaking changes, though.

**Comment by sapegin** [comment]
But we’ll have this issue for everything else as well. Webpack 4 for example. We have this already for extract text plugin. So it’s more generic question than just Babel 6.

**Comment by andywer** [comment]
Yep, that's true. Don't have an answer right now. With a version number in the name (`extract-text3`) you might solve some compatibility issues, but at the same time making it harder to select the right blocks for your setup.

In that case we should definitely put a prominent note to those blocks stating for which webpack versions it's intended to be used.

**Comment by sapegin** [comment]
Done in #217.
