### ISSUE TITLE
Add gitter.im badge

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#198]
[![Gitter chat](https://badges.gitter.im/webpack-blocks.svg)](https://gitter.im/webpack-blocks)

**Comment by sapegin** [comment]
I’m thinking could we somehow automate it with Mrm…

**Comment by andywer** [comment]
In theory: Yes, sure.
In practice: Very difficult, since the badges are not always in the same spot. Usually below the main title, but sometimes on the same line as the main title, just to name to options.

**Comment by sapegin** [comment]
There’s a function for that — https://github.com/sapegin/mrm-core#markdown ;-)

The question is how to run a task on all packages at once ;-)

**Comment by andywer** [comment]
I'd say adding it to the main readme is fine for now.

**Comment by sapegin** [comment]
Boring ;-)

**Comment by sapegin** [comment]
![image 2017-08-25 at 1 33 54 pm](https://user-images.githubusercontent.com/70067/29712422-0f3a720a-899a-11e7-8378-0f8533e23cb4.png)
