### ISSUE TITLE
Debug utility

### ISSUE THREAD

**Issue by sapegin** [andywer/webpack-blocks#200]
It’s often useful to see what config is generated by webpack-blocks and installing stringify-object just for that isn’t that convenient. It would be cool to have an internal debug utility.

Possible API:

```js
module.exports = createConfig([
  /* ... */
]).debug();
```

```js
module.exports = createConfig([
  /* ... */
]).debug('module.rules');
```

`debug` method will nicely print the config (or it’s part) and return the config back so it would still work.

What do you think?

---

I suggest continue using [stringify-object](https://github.com/yeoman/stringify-object) for printing and [Lodash’s get](https://lodash.com/docs/4.17.4#get) method to access deeply nested objects inside the config.

Please send your pull request to `release/1.0` branch.

**Comment by andywer** [comment]
Indeed. Good idea!

This would be way more convenient than using `stringify-object` manually.

**Comment by sapegin** [comment]
Do you like the API?

**Comment by andywer** [comment]
Yeah, I like it :)

**Comment by sapegin** [comment]
Ha, it looks good but I don’t have any idea how to implement it ;-)

**Comment by sapegin** [comment]
Can’t think about anything better than:

```js
module.exports = createConfig([
  /* ... */
], true);

module.exports = createConfig([
  /* ... */
], 'module.rules');
```

**Comment by andywer** [comment]
Well, it's hacky, but we could set a prototype 🙈😅

Or just provide a stand-alone debug function: `debug(config, selector)`.

**Comment by sapegin** [comment]
I can just do `createConfig.debug = ...` but I don’t have access to the config.

> Or just provide a stand-alone debug function: debug(config, selector).

That would work of course but you’ll need to (1) modify import, (2) wrap `createConfig` or `module.exports`.

**Comment by vlad-zhukov** [comment]
How about [`pretty-format`](https://github.com/facebook/jest/tree/master/packages/pretty-format)?

**Comment by sapegin** [comment]
I think for our use case they print too much noise: quotes and types. I’d rather choose something with syntax highlight.

Do you have any ideas on the API? ;-)

**Comment by tdeschryver** [comment]
:wave: just found out about this project and can't wait to try it out.

I think if we want to use the original API proposal we could do it with some kind of build and debug method?

```
function createConfig (initialContext, configSetters) {
  if (!initialContext) {
    throw new Error(`No initial context passed.`)
  }
  if (!Array.isArray(configSetters) || !configSetters.every(isFunction)) {
    throw new Error(`Expected parameter 'configSetters' to be an array of functions.`)
  }

  return {
    build: () => build(initialContext, configSetters) // or maybe not a function and just do .config instead of .build()?
    debug: (selectors) => {
      const config = build()
      // do some debugging stuff here with config and selectors
      return config
   }
}

function build (initialContext, configSetters) {
  const fileType = createFileTypesMapping(defaultFileTypes)
  const context = Object.assign({ fileType }, initialContext)

  invokePreHooks(configSetters, context)
  const config = invokeConfigSetters(configSetters, context)
  const postProcessedConfig = invokePostHooks(configSetters, context, config)
  return postProcessedConfig 
}
```

Another option could be to use a DEBUG env variable and check this variable in `createConfig`?

Just me 2 cents :smile:.

**Comment by sapegin** [comment]
@tdeschryver Thanks for you comments!

I don’t want to change the API just to have a nice debug function ;-) 

> Another option could be to use a DEBUG env variable and check this variable in createConfig?

We can probably use context for that:

```js
module.exports = createConfig([
  debug('module.rules')
  /* ... */
]);
```

**Comment by andywer** [comment]
How about a simple
```js
module.exports = createConfig([
  /* ... */
])
debug(module.exports, 'module.rules')
```
?

**Comment by sapegin** [comment]
Yeah, looks like we can’t really avoid that ;-)

**Comment by andywer** [comment]
@tdeschryver Btw, thx for sharing, though. We always appreciate input on this issues :)

**Comment by sapegin** [comment]
Experimenting with formatting:

![image 2017-09-19 at 1 43 06 pm](https://user-images.githubusercontent.com/70067/30590810-85759f62-9d40-11e7-9071-dd299f06ce00.png)

**Comment by andywer** [comment]
Cool 👍
(Just got to make sure the highlighting is only done in a TTY environment, not when piping to a file or similar)

**Comment by sapegin** [comment]
Good point, though not sure we really need it. I’m going to publish the printer as a separate library first — will be useful for general debugging.

One more example:

![image 2017-09-19 at 2 11 27 pm](https://user-images.githubusercontent.com/70067/30591773-75511630-9d44-11e7-9f92-4cd80a9d59c2.png)

**Comment by andywer** [comment]
Yeah, not sure if we actually need to care for that. Just considering it best practice.
If you use `chalk`, for instance, it will deactivate itself when not run in a TTY :)

**Comment by sapegin** [comment]
I’ve published the pretty printer as a [separate module](https://github.com/sapegin/q-i). So now we can expose this as a `debug` or `inspect` method.
