### ISSUE TITLE
setEnv block

### ISSUE THREAD

**Issue by sapegin** [andywer/webpack-blocks#201]
I assume that most of the `defineConstants` block usages are like this:

```js
defineConstants({
  'process.env.NODE_ENV': process.env.NODE_ENV
}),
```

So it would make sense to have a wrapper around [webpack.EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/):

```js
setEnv(['NODE_ENV', 'DEBUG'])

setEnv({
  NODE_ENV: 'development', // use 'development' unless process.env.NODE_ENV is defined
  DEBUG: false
})
```

I know @andywer isn’t a fan of this idea but I’m sure I could find some supporters 👻 

---

The code would be similar to [defineConstants](https://github.com/andywer/webpack-blocks/blob/release/1.0/packages/webpack/lib/defineConstants.js).

Example implementation: https://github.com/vlad-zhukov/webpack-blocks-more/blob/master/src/setEnv.js

Please send your pull request to `release/1.0` branch.

**Comment by andywer** [comment]
Lol. No, actually the code sample (wrapping `EnvironmentPlugin`) makes sense 👍😉

**Comment by vlad-zhukov** [comment]
I've been using my `setEnv` block for months now. Note that it also sets variables to `process.env` so there is no more need to use things like `cross-env`. However I'm leaning towards using `.env` files recently and this feature becomes obsolete.

**Comment by sapegin** [comment]
@vlad-zhukov Are you interested in sending a PR with `setEnv`? :-) Probably without updating `process.env` to make it more explicit.

**Comment by vlad-zhukov** [comment]
@sapegin sure, I'll have a look later today.

**Comment by sapegin** [comment]
@vlad-zhukov Awesome, thanks!

**Comment by andywer** [comment]
Cool! :)

Time for a `dotenv` block, eh? 😉

**Comment by sapegin** [comment]
@andywer Like this? https://github.com/mrsteele/dotenv-webpack

**Comment by andywer** [comment]
Yes! 🙂

**Comment by vlad-zhukov** [comment]
This can be closed now.
