### ISSUE TITLE
Try lerna hoisting

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#204]
Try [lerna bootstrap --hoist](https://github.com/lerna/lerna/blob/master/doc/hoist.md) to improve installation time for dev set-up.

**Comment by sapegin** [comment]
Shouldn’t we rather just move all dev dependencies to the main `package.json`? Do we really need testing and linting dependencies on a package level? What’s the best practice for Lerna?

**Comment by andywer** [comment]
Sure, we could. Just learned about that feature & it seemed to be a clean approach.

**Comment by vlad-zhukov** [comment]
This feature looks like yarn workspaces but worse.

**Comment by andywer** [comment]
Well, it was just a quick thought... No hard feelings about it 😉

**Comment by andywer** [comment]
Closing it for the time being.
