### ISSUE TITLE
test-app on Windows

### ISSUE THREAD

**Issue by tdeschryver** [andywer/webpack-blocks#215]
The test-app is throwing errors when building or starting on windows because of `NODE_ENV=xxx`

Proposal:
Using [kentcdodds/cross-env](https://github.com/kentcdodds/cross-env) so we can do `cross-env NODE_ENV=xxx`

**Comment by sapegin** [comment]
That would be very good! We even suggest it in the docs. Would you mind sending a PR for that?

**Comment by tdeschryver** [comment]
Sure no problemo!

**Comment by vlad-zhukov** [comment]
Closed by #220
