### ISSUE TITLE
Add end-to-end testing

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#22]
Right now there are unit tests and an integration test that tests the interaction between the packages.

There shall be tests for not only creating a config, but actually make webpack run them!

**Comment by andywer** [comment]
Hopefully this will prevent regressions like #20 in the future.

**Comment by eXon** [comment]
It is possible to compile the exact same way within Node.js and save the result within an in-memory filesystem. I think this would be much better/faster than running the CLI and would have the exact same result.

Reference: https://webpack.github.io/docs/node.js-api.html

**Comment by andywer** [comment]
@eXon Yesterday evening I added some end-to-end tests to the upcoming `webpack2` block and pretty much did it like this :) [packages/webpack2/__tests__/end-to-end.test.js](https://github.com/andywer/webpack-blocks/blob/feature/webpack2/packages/webpack2/__tests__/end-to-end.test.js)

Without the in-memory FS, though. It just writes the output artefacts into a local, .gitignore-ed `build/` directory.

**Comment by andywer** [comment]
PS: But there are no dev-server e2e tests yet. It's more work, since we will have to launch the dev-server, request the bundle from it and stop the server again. And we must set the port to some free port, not the default one.

**Comment by eXon** [comment]
It's very easy to setup, you'll have to barely change anything (see https://webpack.github.io/docs/node.js-api.html#compile-to-memory). It has the benefit of being able to parallelize your tests and make sure to reset the file system for every test.

For the dev-server, I'm not sure you need to run it outside checking if the generated webpack config is right.

**Comment by andywer** [comment]
@eXon Interesting! I think I didn't scroll so far down before 😅
