### ISSUE TITLE
update webpack-dev-server

### ISSUE THREAD

**Issue by Geczy** [andywer/webpack-blocks#227]
To 2.9.x PLEASE

**Comment by Geczy** [comment]
For the devServer block

**Comment by sapegin** [comment]
Try to reinstall webpack-blocks, if you’re using 1.0 beta it should install the latest 2.x:

https://github.com/andywer/webpack-blocks/blob/e0cc86304982b8832377a6baea821ec3b7335bc6/packages/dev-server/package.json#L22

Feel free to send a pull request!

**Comment by Geczy** [comment]
Thanks, removing and re-adding fixes it
