### ISSUE TITLE
Proper preset support

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#24]
In fact webpack-blocks already makes it quite easy to group blocks. But it would be more convenient if [@webpack-blocks/core](https://github.com/andywer/webpack-blocks/blob/master/packages/core/src/index.js) would export another function that works like `env()`, but without checking the environment.

## How it could look like

```js
const { group } = require('@webpack-blocks/core')
const babel = require('@webpack-blocks/babel6')
const postcss = require('@webpack-blocks/postcss')

const defaultPostcssPlugins = [ /**/ ]

module.exports = function myPreset ({ addPostcssPlugins }) {
  const postcssPlugins = defaultPostcssPlugins.concat(addPostcssPlugins || [])

  return group([
    babel(),
    postcss(postcssPlugins)
  ])
}
```

## How it could be used

```js
// webpack.config.js
const { createConfig, entryPoint, setOutput } = require('@webpack-blocks/webpack')
const myPreset = require('my-preset')

module.exports = createConfig([
  myPreset(),
  entryPoint('./src/app'),
  setOutput('./build/bundle.js')
])
```

**Comment by eXon** [comment]
I think this would be very helpful.

It would be great to be able to write (same for `createConfig` actually): 

```js
groupBlocks(
  babel(),
  postcss(postcssPlugins)
)
```

**Comment by andywer** [comment]
@eXon Hmm. I thought about that too when I started designing the API. But is there a real benefit?

Right now `createConfig()` takes just one parameter which is the blocks array. But at least there is an option to add a second one if there is a need to do so in future. If you pass every block as a single parameter this door will be shut forever.

I also think that it's more complicated to provide working type information (jsdoc, or in future maybe flow-type or so) for a function with an unlimited number of params.

**Comment by andywer** [comment]
Note: Just renamed `groupBlocks` function => `group` (in the example at the top). It's clean, it's short and yet easy to understand :)

**Comment by andreiglingeanu** [comment]
I'm having a question:

You guys are thinking about a way to `group` blocks. How do I override/disable/add something onto a `group`? 

Am I able to do something like this and expect that the `setOutput` block would be overided?

```javascript
let group1 = group(
  entryPoint('./src/app'),
  setOutput('./build/bundle.js')
);

let group2 = group(
  group1,
  setOutput('./another-build-dir/bundle.js')
);
```

I even may want to remove a block (extract text?) from a group. If there is a way group blocks, why there shouldn't be one to remove some block from a group. Does this make any sense?

**Comment by andywer** [comment]
Hey @andreiglingeanu.

Basically: `group()` returns a new block that is the combination of all single blocks of the group. You pass it to `createConfig()` along with other blocks, so adding is trivial. Overriding (like `setOutput()`) already works. Removing stuff from a group won't work, but you can make your group configurable.

A little example to demonstrate what I mean:

```js
// webpack.config.js

module.exports = createConfig([
  myPreset(false),
  setOutput('./another-build-dir/bundle.js')
])
```
```js
// myPreset.js
module.exports = function myPreset (doExtractText = true) {
  return group([
    entryPoint('./src/app'),
    setOutput('./build/bundle.js')
  ].concat(
    doExtractText ? [ extractText() ] : []
  ))
}
```

Hope that answers your questions :)
But feel free to provide feedback either way ;)

**Comment by andreiglingeanu** [comment]
> Overriding (like `setOutput()`) already works.

That's awesome!

Configurable group kinda works for me and it looks a bit more predictable actually! 

The behavior of a group will depend only on its config or the overrides of _already_ known blocks, which is very nice because in order for users to modify behavior you'll have to follow the block specification and I like that a lot!

The thing is that I need a way to predictably configure webpack (and webpack multi compiler) based on some specific login and I also need a way to modify/override/disable bits of configuration. And it looks like `webpack-blocks` is right tool for this job. I'll probably take a closer look at webpack-blocks (and your `feature/webpack2` branch) and will throw more ideas/questions along the way.

**Comment by andreiglingeanu** [comment]
@andywer I also like how you allow infinite number of arguments and an array of blocks for the `group()` function.

**Comment by eXon** [comment]
Just a quick comment on the case of using infinite arguments. You're not blocking yourself from adding an addition argument for options latter (I hope we don't need that though, not sure what option we might need there).

`group(block1, block2, block3, options)` could be easily detectable. All you need to do really is check if the last argument is an object and if so, it is the options. If it's a function, it's just the last block.

Again, this is just syntaxic sugar but I like better. 

For the documentation, it's pretty easy to document: `@param {...*} var_args`

For the sake of simplicity you could also drop the array and if you really want it, you could use group.apply(null, [block1, block2, block3])

**Comment by andywer** [comment]
Hey guys!

@andreiglingeanu Sounds great :) Will implement `group()` plus some other stuff the next days.
@eXon Yeah, detecting wouldn't be hard, by it does not feel very clean and I would like to have one way to do it, also in order to not confuse users with different syntactics.

Tell you what: I will do a poll on twitter (will send you the link, of course) about *array or not array calls* and open a new issue for that discussion.

**Comment by andreiglingeanu** [comment]
> I would like to have one way to do it

In this case, take the array path. Everyone will look for ways to dynamically use this thing and array syntax is a bit more prepared for that. I'd rather keep users away from having to `.apply()` in order to build a group dynamically.
