### ISSUE TITLE
Have setOutput accept an object

### ISSUE THREAD

**Issue by AlahmadiQ8** [andywer/webpack-blocks#245]
I have the following use case in webpack: 

```javascript
{
  output {
    filename: 'js/index.js',
    path: 'build',
}
```

currently `setOutput` only accepts a string. it would be nice to have it also accept an object to configure `filename` and `path`. Perhaps something like this: 

```javascript
function setOutput (output) {
  if (typeof output === 'string') {
    output = {
      filename: path.basename(output) || 'bundle.js',
      path: path.resolve(path.dirname(output) || './build')
    }
  } else if (typeof output === 'object') {
    output = {
      filename: output.filename || 'bundle.js',
      path: output.path || './build'
    }
  }

  return (context, util) => util.merge({ output })
}
```

**Comment by andywer** [comment]
Hey @AlahmadiQ8.

You can pass an `output` object if you want to. See the `webpack` blocks's [README](https://github.com/andywer/webpack-blocks/tree/master/packages/webpack#setoutputoutput-stringobject).

Feel free to re-open the issue if that doesn't work 😉
