### ISSUE TITLE
createConfig from available webpack base config

### ISSUE THREAD

**Issue by DrSensor** [andywer/webpack-blocks#248]
Necessery when using template project that have their own cli like storybook.
The usage may be something like:
```js
module.exports = (storybookBaseConfig) => {
  return createConfig(storybookBaseConfig, [
    /** extend the config here */
  ]) 
} 
```

**Comment by jvanbruegge** [comment]
You can do this with the customConfig block:
```js
const { customConfig, createConfig } = require('webpack-blocks');

module.exports = (storyboardConfig) => createConfig([
    customConfig(storyboardConfig),
    //...
]);

**Comment by DrSensor** [comment]
Thanks, thats help me. Also, it would be nice in Readme to have section how to extend available webpack configuration.

**Comment by jvanbruegge** [comment]
[This](https://github.com/andywer/webpack-blocks/blob/master/packages/webpack/README.md) is linked unter the helpers section, isnt that enough?

**Comment by DrSensor** [comment]
Ah.. my bad. Because I browse in 📱, this https://github.com/andywer/webpack-blocks/blob/master/README.md#shorthand-setters only show me the directory, not the Readme

**Comment by jvanbruegge** [comment]
No problem

**Comment by andywer** [comment]
👍

Yeah, I also stumbled about the mobile site not showing the README before...
Closing.
