### ISSUE TITLE
Block internals: Pre- and post-processing hooks

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#25]
As @eXon pointed out in #17 it might be beneficial to enable webpack blocks to define post-processing functions. That could allow you to define constants multiple times in multiple blocks, but eventually get a single `webpack.DefinePlugin` instance.

Another use case is the `dev-server` block which is currently being changed (#21). It adds a dev-server entry point to every chunk in the `entry` object. Right now this means that the `dev-server` is used after setting all your entry points. A post-processing step defined by `dev-server` would allow you to use your `entry` and `dev-server` blocks in random order.

A pre-processing might be desirable to add custom mime types before any the blocks are run.

Open for discussion :)

**Comment by andywer** [comment]
Another feature directly related to this: Have a context object in the webpack config object or independent from it to store metadata to share between blocks.

Another use case: `sourceMap()` currently enables source maps on JS code only. With a pre-process step it could set a flag on the context object to indicate to other blocks to enable source maps on the `css-loader` as well, for example.

**Comment by eXon** [comment]
It certainly need a context object that every block can access. I happen to think the fileTypes argument should disappear.

The context could contain the fileTypes and more and it would be shared between every blocks.

The big question here in my opinion is how do we hook those block to pre/post processing? Are they doing it as soon as you import the Node.js module? Are we hooking when you hook a block for the first time using a unique key. Are we hooking using an EventEmitter within the block before returning the function?

I guess we'll have to playaround to see what works the best.

**Comment by andywer** [comment]
Published in version 0.3.0.
