### ISSUE TITLE
Allow negations in match

### ISSUE THREAD

**Issue by marcofugaro** [andywer/webpack-blocks#252]
Taken from the readme:
```js
match('*.css', { exclude: path.resolve('node_modules') }, [
  css(),
]),
```
I think this would be better rewritten as 
```js
match(['*.css', '!*node_modules*'], [
  css(),
]),
```
or, in my use-case 
```js
match(['*.css', '!*.module.css'], [
  css(),
]),
```

Looking at the code, I think the negations could be extracted from the array and passed to the exclude here:

https://github.com/andywer/webpack-blocks/blob/d84ddd20b35ed8fc68f7ebd3e9e565e49d95db39/packages/core/lib/match.js#L29

Webpack accepts regexes fine in the exclude field.

What do you guys think? I can take a stab at it.

**Comment by andywer** [comment]
I like it! :)

Would be happy to review a PR introducing that.

**Comment by andywer** [comment]
And thanks for sharing your idea, @marcofugaro

**Comment by vlad-zhukov** [comment]
Negations can happen anywhere in a pattern, how are we going to handle it? Is it going to be predictable?
And also `glob-to-regexp` doesn't support many glob features including negations.

**Comment by andywer** [comment]
> Negations can happen anywhere in a pattern

Really? I was thinking about the negation of the whole pattern (`!` in the very front) only. Just as a nicer way to specify exclusions.

> And also glob-to-regexp doesn't support (...) negations

True, but could quite easily be worked around by doing this, I think:

```js
const negations = patterns.filter(pattern => pattern.startsWith('!')).map(pattern => pattern.substr(1))
match.test = patterns.filter(pattern => !pattern.startsWith('!')).map(regexify)
match.exclude = options.exclude.concat(negations.map(regexify))
```

**Comment by marcofugaro** [comment]
Yes, I think that's it's way too much overhead to support also negations anywhere in a pattern. 
Probably not worth it since negations are always used at the start.

**Comment by marcofugaro** [comment]
By the way, @andywer do you think we still need to support the `options` parameter (the second one) in the `match()`?

**Comment by andywer** [comment]
Good question. I would keep it, since it doesn't cost us anything except maintenance of a couple of LOC. There might still be scenarios where you want to pass a more elaborate include/exclude configuration.

But no hard feelings either way.

**Comment by marcofugaro** [comment]
Alright, done it. It was a pain to handle all the cases.
