### ISSUE TITLE
Support for webpack 4

### ISSUE THREAD

**Issue by marcofugaro** [andywer/webpack-blocks#255]
Webpack4 [~~is currently in beta~~](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2) [has been released](https://github.com/webpack/webpack/releases/tag/v4.0.0), quite some things changed.

Taking a look from the [changelog](https://github.com/webpack/webpack/releases/tag/v4.0.0-beta.0), here is what needs to be done in order to support webpack 4:

- [x] Add a `mode` block, I imagined it something like `mode('production', { minimize: false })` since 
  > You can configure this in detail with the flags in optimization.* (build your custom mode)
- [x] Update the uglify block, now under `optimization.minimizer[0]`
- [x] Update the devServer block (`NamedModulesPlugin` plugin)
- [ ] ~[`webpack-dev-server`](https://github.com/webpack/webpack-dev-server) has been deprecated in favour of [`webpack-serve`](https://github.com/webpack-contrib/webpack-serve)~
- [ ] [`extract-text-webpack-plugin`](https://github.com/webpack-contrib/extract-text-webpack-plugin) is deprecated for CSS in favour of [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin)
- [x] Upgrade all dependencies (wait for the plugins to release new versions)

thank you! I probably missed something else...

**Comment by andywer** [comment]
Thx for opening the issue, @marcofugaro!

I like the `mode` block proposal.

**Comment by vlad-zhukov** [comment]
It looks like we are going to have a major bump of `webpack-blocks` with the webpack 4 support. @andywer what do you think about finalising v1 and start working on v2?

**Comment by marcofugaro** [comment]
I forgot to add, there is probably the need for an `optimization` block of some sort.
An example would be `optimization({ sideEffects: false })` or a way to configure `optimization.splitChunks`, but I'm not sure how to go about it.

**Comment by vlad-zhukov** [comment]
@marcofugaro is't the `mode` block you proposed works like this?

**Comment by marcofugaro** [comment]
@vlad-zhukov yeah but `optimization` contains stuff also not related and not influenced by the mode.
`splitChunks` and `sideEffects` are the only two I could find. Search for `optimization` in the [new changelog](https://github.com/webpack/webpack/releases/tag/v4.0.0)

**Comment by andywer** [comment]
@vlad-zhukov Yeah, I totally agree. We can take webpack-blocks as it is and make it the final v1.0.0. Can then do a major bump for webpack 4.

I am just terribly busy and have little time. Help from all contributors is highly appreciated 😊

**Comment by dmitmel** [comment]
@marcofugaro Could you, please, outline which features _need to be done in order to support webpack 4_?

**Comment by marcofugaro** [comment]
@dmitmel what do you mean? All of them are necessary

**Comment by dmitmel** [comment]
@marcofugaro

> what do you mean?
I want to open a PR so I must know what features to add.

> All of them are necessary
Do you mean features described in the issue description?

**Comment by marcofugaro** [comment]
> Do you mean features described in the issue description?

Yup.

**Comment by dmitmel** [comment]
I'm working on webpack 4 features but I'm stuck with the `mode` block. I have some ideas on how this block can be used:

1. **To simply set the mode** (well, in this case, a better name for this block would be `setMode`).
2. **To configure `optimization` settings based on the current mode**. This would require a `setMode` function for setting mode and adding it to the context.

Any thoughts?

_P.S._ I personally like more the first idea because we already have `env` function for setting env-based settings.

**Comment by dmitmel** [comment]
How do you think, should `NODE_ENV` be used as the default value for `mode`?

**Comment by andywer** [comment]
> How do you think, should `NODE_ENV` be used as the default value for `mode`?

I'd say explicit is better than implicit, so let's set the `mode()`/`setMode()` explicitly to production or development. There is no more need to set `NODE_ENV` in the config then, too, since:

> (webpack 4 changelog; `mode` config:) process.env.NODE_ENV are set to production or development (only in built code, not in config)

But it might make sense to put the mode into the context, anyhow, since it's a pretty important setting that you might want to react to in other blocks as well.

**Comment by vlad-zhukov** [comment]
I'd make the `mode` function also take a second parameter `optimization` instead of introducing 2 blocks.

```js
mode('development', {
	splitChunks: 'all',
});
```

**Comment by dmitmel** [comment]
@vlad-zhukov It's better two use two blocks because each of them has a different task.

**Comment by marcofugaro** [comment]
@dmitmel Some of the options in `optimization` will override the ones set by the production or development mode, so it makes sense to make it more explicit in the `mode` block.

From the changelog:
> You can configure this in detail with the flags in optimization.* (build your custom mode)

Those options are `optimization.minimize`, `optimization.noEmitOnErrors`, `optimization.concatenateModules`, `optimization.namedModules` and probably some more, they canged based on the mode.

Making it more explicit leads to less buggy webpack config.

I think it should be supported both an optional parameter in the `mode` block and an `optimization` block for mode-independent features like `optimization.splitChunks`

**Comment by dmitmel** [comment]
@vlad-zhukov @marcofugaro The second parameter is great when there are separate configurations for development and production. I didn't understand you at first because I put webpack config for both prod and dev into one file if there are a lot of common settings.

**Comment by dannyphillips** [comment]
Any updates on this?

**Comment by vlad-zhukov** [comment]
Updated the OP message with the `webpack-serve`.

**Comment by dmitmel** [comment]
@dannyphillips Upgrade to webpack 4 requires a lot of breaking changes in webpack-blocks, so we have to release a new major version (`v1.0` -> `v2.0`).

**Comment by vlad-zhukov** [comment]
As I pointed in #279, [Extract Text Plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) is deprecated for CSS in favour of [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin). Do we need to keep the `extract-text` block in v2? What are the other use cases for it?

**Comment by andywer** [comment]
Would be fine to me to replace `extractText` by `extractCSS` (?). But also not sure if there is still some common use case for the extract-text plugin.

**Comment by andywer** [comment]
FYI: Published v2.0.0-alpha with webpack 4 support.

Install using `npm install --save-dev webpack-blocks@next`.

**Comment by IngenieroLata** [comment]
I found and error using `devServer` without `entryPoint`: 
```batchfile
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
```

After taking a look at the devServer code seems like the Webpack's default entry is being replaced with nothing. 
Any fix for that? Maybe the block's entry default shouldn't be there since Webpack 4 defaults it to `'src/index'`?

**Comment by dmitmel** [comment]
Hmmm, why does the `devServer` block add an entry in the first place? Isn't this a job for the `entry` block?

**Comment by IngenieroLata** [comment]
@dmitmel yep, maybe for a silent error or something? check this lines: [25](https://github.com/andywer/webpack-blocks/blob/f4a07548945126dedbb1e498ba305678137a0a7a/packages/dev-server/index.js#L25) and [50](https://github.com/andywer/webpack-blocks/blob/f4a07548945126dedbb1e498ba305678137a0a7a/packages/dev-server/index.js#L50) 
I'd say it's not necesary default "entry" as nothing anymore under devServer.

**Comment by vlad-zhukov** [comment]
@IngenieroLata Does `webpack-serve` work for you? I tried to write a block for it some time ago but couldn't make it start running.

**Comment by IngenieroLata** [comment]
@vlad-zhukov yes it works for me, but there are certain options that only work with the command line. https://github.com/webpack-contrib/webpack-serve/issues/237 

I think `webpack-serve` docs are not clear about which options can be under cosmiconfig and which ones doesn't.

```json
...
"scripts": {
    "start": "webpack-serve --log-level error",
},
...
```
On the other hand, the hot-client seems to have some issues https://github.com/webpack-contrib/webpack-serve/issues/218

**Comment by marcofugaro** [comment]
Hey, I tried to update the mini-css-extract block but couldn't figure out all the logic that is inside the current extract-text block, and was afraid I might mess something up. 

Here is a basic block of the `mini-css-extract-plugin` if anyone wants to take a stab at it.

```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

function extractCss(options) {
  return (context, util) => util.merge({ 
    module: {
      rules: [
        Object.assign({
          test: /\.css$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
            },
          ],
        }, context.match)
      ]
    },
    plugins: [
      new MiniCssExtractPlugin(options),
    ],
  }
}

// usage
extractCss({
  filename: 'app.[contenthash:8].css',
  chunkFilename: '[name].[contenthash:8].chunk.css',
})
```

**Comment by marcofugaro** [comment]
Welp, they did a 180 and deprecated `webpack-serve` instead.

https://github.com/webpack-contrib/webpack-serve

**Comment by andywer** [comment]
Well, less work for us... 🙈🙈

Thx for pointing out!

**Comment by Telokis** [comment]
May I ask what the status of this issue is?  
It seems that everything has been resolved (considering the `extractCss` snippet three post above mine)

**Comment by andywer** [comment]
Thanks for pointing out, @Telokis! Yes, I think that issue has been resolved long ago.

If anyone likes to disagree (but I sincerely doubt that), now is your chance 😉
