### ISSUE TITLE
@webpack-blocks/babel-loader: how to disable exclude node_modules

### ISSUE THREAD

**Issue by alexander-heimbuch** [andywer/webpack-blocks#258]
Hey,
I stumbled across an issue with to not transpiled artefacts in one of my bundles. I could trace this back to a dependency that exports es6 code. Unfortunately I couldn't find a way to overwrite `exclude: /node_modules/,` in the babel loader rule config. What did I miss?

Best,
Alex

**Comment by zcei** [comment]
Hej @alexander-heimbuch,

you should be able to overwrite the `exclude` by using a custom `match` block around the `babel` block.

For an example see the [Usage section](https://github.com/andywer/webpack-blocks/tree/master/packages/babel#usage) of the `babel` block.

**Comment by alexander-heimbuch** [comment]
@zcei Yes, I tried that but because of `Object.assigns` extension logic I have to set `exclude` to a specific value. I didn't find a way to remove it completely. As a workaround I added a regex that does not find a match to overwrite it. But still this is a dirty hack and kind of destroys the purity of webpack-blocks :(

**Comment by zcei** [comment]
Ah I see, basically we're guarding ourselves from overwriting the default excludes here:
https://github.com/andywer/webpack-blocks/blob/d130547b2ee9cb046b56570132b846657debccfb/packages/core/lib/match.js#L39-L44

**Comment by andywer** [comment]
@zcei The code you mentioned is on `master` and we still haven't deployed yet (d'oh!). The current reason for the trouble is here:
<https://github.com/andywer/webpack-blocks/blob/f7fc56896f3fa039bcba5483a02c664aeaa348d9/packages/core/lib/match.js#L28-L30>

We should really deploy this stuff...

But: I think the new (still undeployed) code will actually fix the issue. The `if (exclusions.length > 0)` is not an issue. It just adds the negative globs (like `!node_modules`) to `options.exclusions`.

Suggestion: Let's add a unit test for `match()` that checks that we can actually override default exclusions with an `exclude: null` or `exclude: []`.

@alexander-heimbuch Would setting `exclude: null` to override the default be fine?

**Comment by alexander-heimbuch** [comment]
@andywer That would be perfect 👍

**Comment by vlad-zhukov** [comment]
@andywer 

> Suggestion: Let's add a unit test for `match()` that checks that we can actually override default exclusions with an `exclude: null` or `exclude: []`.

[But there is such test already](https://github.com/andywer/webpack-blocks/pull/250/files#diff-6304e5ee1acd50b6dba567aa32664d03)... See #250, `match('*.js', { exclude: [] }` currently works with the released version, and `match('*.js', { exclude: null })` already works on the master branch.

**Comment by andywer** [comment]
Thx for sharing the link, but that test doesn't match our issue. We need to test if `exclude: null` can actually override a default `exclude` and that seems broken 😉

See also:
<https://github.com/andywer/webpack-blocks/blob/7c9259767be97c65cdd9ee011a36997a8ed175a4/packages/babel/index.js#L39-L45>

**Comment by vlad-zhukov** [comment]
But it __does__ override it as shown in that test!

**Comment by andywer** [comment]
Ahh, my bad. Didn't see the `babel()`.

Well, that's strange then. In this case it should work already...

**Comment by alexander-heimbuch** [comment]
@andywer I can verify that @vlad-zhukov solution works 👍 So that's basically what I needed, thanks for the lively discussion.

**Comment by andywer** [comment]
Cool! Just to wrap it up:

For now you have to use `exclude: []`, until we release the new version, right?

**Comment by vlad-zhukov** [comment]
Correct
