### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by dmitmel** [andywer/webpack-blocks#262]
While refactoring code, I noticed that the codebase contains _different coding styles_ because many people contribute to this project. This causes some problems like inconsistent line length.

My suggestions are:

- **Use [Prettier](https://prettier.io/) instead of Standard**, because Prettier produces more _consistent_ code. However, Prettier doesn't follow the JavaScript Standard Style, e.g. it doesn't put a space after function name in declarations.
- **Use ESLint** with something like [the Airbnb preset](https://github.com/airbnb/javascript).

**Comment by andywer** [comment]
Could you please link to those places with different code styles?

Using prettier has been a topic for quite some time. I don't see any reason against, there was just no time yet to do that.

How would the Airbnb ruleset change anything? Because it's stricter?

**Comment by dmitmel** [comment]
@andywer

> Using prettier has been a topic for quite some time. I don't see any reason against, there was just no time yet to do that.

Setting up Prettier and ESLint is really easy, I've even created an [ESLint preset](https://github.com/dmitmel/eslint-preset-dmitmel) that automatically configures Prettier and the Airbnb preset.

> How would the Airbnb ruleset change anything? Because it's stricter?

No. It's just my preference.

**Comment by farism** [comment]
I prefer husky + prettier and no eslint. I understand that eslint handles a whole class of things that prettier does not, but I kind of like to talk about those things during code review anyway.

**Comment by andywer** [comment]
> I understand that eslint handles a whole class of things that prettier does not, but I kind of like to talk about those things during code review anyway.

That is true for code style, but the important "whole class of things that prettier does not handle" is stuff like checking for unused variables, broken references, etc. That's what prettier cannot provide. I say it should not be the reviewer's responsibility either, since it can be reliably checked by software 😉

**Comment by andywer** [comment]
Is this issue still relevant, now that we have prettier in the v2.0 branch?

**Comment by vlad-zhukov** [comment]
We've got both Prettier and ESLint. Now we can add more ESLint rules over time.
