### ISSUE TITLE
uglify package 1.0.0 doesn't match what is in the npm registry

### ISSUE THREAD

**Issue by DingoEatingFuzz** [andywer/webpack-blocks#278]
Were tags force pushed without a follow up `npm publish`?

**Steps to reproduce:**
1. Make a new directory
2. Run `npm i @webpack-blocks/uglify`
3. Open the relevant file `vim node_modules/@webpack-blocks/uglify/index.js`
4. See that the default options use the dated format:
  ```js
  options = webpackMerge({
    parallel: {
      cache: true
    },
    uglifyOptions: {
      compress: {
        warnings: false
      }
    }
  }, options)
  ```
5. Compare this to what is in source control @1.0.0
https://github.com/andywer/webpack-blocks/blob/a4d01d67ba9acb3aba17b0cb1f431af1e65d69f9/packages/uglify/index.js#L16-L25

Note the difference.

The code in Github uses default options that pass uglifyjs-webpack-plugin validation, but the code in the npm registry does not.

In the interim, I and others can specify options explicitly, but these changes should be published.

**Comment by vlad-zhukov** [comment]
The npm tags have been messed up for this package and it's a known issue. The `latest` points to 1.0.0, but there is a newer version 1.1.0. You can fix your problem by installing it directly with `npm i @webpack-blocks/uglify@1.1.0`.

**Comment by andywer** [comment]
Ohh, really? I wasn't aware of that (or I forgot? 🤔).

Let me fix that...

```
➜ npm dist-tag add @webpack-blocks/uglify@1.1.0 latest
+latest: @webpack-blocks/uglify@1.1.0

~ took 18s 
➜ 
```

npmjs.com shows `1.1.0` as latest version now.

**Comment by DingoEatingFuzz** [comment]
Thanks for the fast turnaround on this! I'm loving using this lib ❤️
