### ISSUE TITLE
Webpack blocks for webpack ^4.0.0 and babel ^7.0.0

### ISSUE THREAD

**Issue by pravdomil** [andywer/webpack-blocks#284]
here https://github.com/pravdomil/webpack-blocks

**Comment by dmitmel** [comment]
@pravdomil Support for Webpack 4 and Babel 7 are planned features for v2.0, you can follow progress in [this issue](https://github.com/andywer/webpack-blocks/issues/264).

**Comment by pravdomil** [comment]
great!
