### ISSUE TITLE
Tag a new version for update peer dependencies commit

### ISSUE THREAD

**Issue by jermspeaks** [andywer/webpack-blocks#308]
When I update dependencies, I'm getting a warning from my package manager:

`warning "webpack-blocks > @webpack-blocks/assets@2.0.0" has unmet peer dependency "@webpack-blocks/core@^2.0.0-rc".`

This has been fixed in the following commit: dca0f219a6551b727494a53e043f87694422a546

Can we update the release to `v2.0.1` so we can utilize this new version? 

Thanks!

**Comment by andywer** [comment]
Done! 🙌

Sorry for the late response 😉
