### ISSUE TITLE
API: Array argument vs. many arguments

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#38]
This is the discussion for the API syntactics suggestion which started in #24.

## How it works now

```js
createConfig([
  block1(),
  block2(),
  block3()
])
```

## Alternative

```js
createConfig(
  block1(),
  block2(),
  block3()
)
```

## The question

Are there strong feelings towards one of the syntaxes or another? This affects `createConfig()`, `env()` and (not yet implemented) `group()`.

@eXon @andreiglingeanu

**Comment by andywer** [comment]
Here is the poll: https://twitter.com/andywritescode/status/809818403393388548

**Comment by andreiglingeanu** [comment]
How hard may be to support both of them?

**Comment by andywer** [comment]
Let's stick to one way.

"In this case, take the array path. Everyone will look for ways to dynamically use this thing and array syntax is a bit more prepared for that. I'd rather keep users away from having to .apply() in order to build a group dynamically."

Very good point 👍 Especially for the `group()` case.

**Comment by eXon** [comment]
Let's stick to what we have if we can't find a strong reason enough to break the API.

**Comment by andywer** [comment]
### Quick update
Because of the aforementioned reasons and the current state of the poll which currently looks like this:
<img width="591" alt="bildschirmfoto 2016-12-17 um 17 19 25" src="https://cloud.githubusercontent.com/assets/1842462/21288223/607f21ca-c47d-11e6-8c86-de01dc6b9a7a.png">

I am looking forward to leave the API as it is.

But I'm still glad we are having this discussion, since the API is now based on some good arguments and a public poll instead of just my gut feeling 😉
