### ISSUE TITLE
Test App not working

### ISSUE THREAD

**Issue by TheWolfNL** [andywer/webpack-blocks#39]
I get the following error when trying to run the test app, eventhough i've ran yarn, and npm install both.

> sh: webpack-dev-server: command not found

![](http://i.imgur.com/3slcgBR.png)

**Comment by andywer** [comment]
Hey @TheWolfNL.

What does an `ls node_modules/` print on your machine (in the `test-app` directory)?

Installing the depedencies with yarn didn't work for me at all... Getting strange errors. Maybe yarn doesn't like scoped packages very much yet. With npm it did work, though.

I know the chances are low, but let's try a `rm -rf node_modules && npm i`.

**Comment by TheWolfNL** [comment]
Thnx @andywer that fixed it

> I know the chances are low, but let's try a `rm -rf node_modules && npm i`.
