### ISSUE TITLE
Idea: Configuration file wizard webapp

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#4]
Build a simple webapp for creating webpack configs.

Input:
- Entry point(s)
- Output file path(s)
- Features like `babel`, `dev-server`/`dashboard`, `postcss`, `css modules`, `sass`, ... (select babel, dev-server and autoprefixer by default)

Output:
- Webpack config file (+ download button)

Show *next steps*:
- `start` and `build` scripts to add to `package.json`
- How to run the dev server / how to trigger a production build

**Comment by vitorbal** [comment]
Thank you for the awesome project! This is a great idea and I plan on trying this for my next app.

Just throwing it out there, what do you think about alternatively making the wizard a CLI tool? We use [Inquirer](https://github.com/sboudrias/Inquirer.js) for [ESLint's --init command](http://eslint.org/docs/user-guide/command-line-interface#init) and at the end of the process create all the necessary config files, install all npm packages, etc. based on your answers.

**Comment by andywer** [comment]
@vitorbal That would be #7 then :)

But maybe I should close this issue for now in favor of #7 which covers a CLI tool and presets.

**Comment by andywer** [comment]
@vitorbal PS: But feel free to add further thoughts here or in the other issue ;)

**Comment by vitorbal** [comment]
@andywer Oops, sorry, totally missed #7. Thanks for the quick reply :) I'll add some further thoughts to #7 if I think of anything 👍
