### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#5]
Webpack 2 shall be supported!

Backed by [public interest](https://twitter.com/andywritescode/status/800392620975472645).

To Do:
- [x] Create new webpack blocks: `webpack2`, `dev-server2`, `extract-text2`
- [x] Update test app
- [x] Make `webpack` and `webpack2` blocks DRY

**Comment by andywer** [comment]
Unfortunately there is a regression in recent webpack 2 beta versions crashing the *extract text plugin*: [webpack/extract-text-webpack-plugin#214](https://github.com/webpack/extract-text-webpack-plugin/issues/214#issuecomment-249647762)

That complicates stuff... At least if you need the plugin.

**Comment by andywer** [comment]
There is a working demo in https://github.com/andywer/webpack-blocks/tree/feature/webpack2

**Comment by porfirioribeiro** [comment]
Would be greate to have @beta packages on npm soon!

**Comment by andywer** [comment]
@porfirioribeiro Sure! There is a really good chance you get to try the beta by Friday or end of the week.

Feel free to post a "ping" here on this issue on Saturday if it hasn't arrived by then 😉

**Comment by d3viant0ne** [comment]
@andywer - I'm down to play guinea pig on this or help bring the remaining tasks home. Code, docs w/e. I have a non trivial project ready and waiting to implement blocks for Webpack v2 :)

**Comment by andywer** [comment]
@d3viant0ne Sounds terrific! :) I will publish the packages with a 'beta'-suffixed version tomorrow, I think.

Some real-world use case feedback would be awesome. Feel free to open PRs as you go or post your experiences here in the issues :)
(Maybe [gitter](https://gitter.im/) would be handy...)

**Comment by andywer** [comment]
Here it is!

🚀 Just published the `webpack2`, `dev-server2` and `extract-text2` block as version `0.1.0-beta`

Also added a small usage note to the [README](https://github.com/andywer/webpack-blocks#webpack-2).

Webpack2 feature branch is not yet merged, but that should be fine for now.

Try it and share how it works for you if you have got some time :)

**Comment by andywer** [comment]
Before I forget...

The `postcss` block has been updated to support the latest `postcss-loader` and you can now put your postcss plugin configuration into a `postcss.config.js` file.

**Please do so and don't use the `postcss` block's plugins parameter when using `webpack2` 😉**

**Comment by andywer** [comment]
Santa is coming to town, carrying a big bag of features and improvements for webpack-blocks 🎄🎄

Webpack 2 blocks have been merged into the `release/v0.3` branch, release branch is tagged and ready to ship. Stay tuned! 📻

**Comment by andywer** [comment]
Published in version 0.3.0 🎉
Read the release notes [here](https://github.com/andywer/webpack-blocks/releases/tag/v0.3.0).
