### ISSUE TITLE
Support for react-hot loader

### ISSUE THREAD

**Issue by eXon** [andywer/webpack-blocks#56]
Right now there is no support for the react-hot loader : https://github.com/gaearon/react-hot-loader

Basically what you need is the devServer enabled (already got the block for that) and the 'react-hot' loader before the 'babel-loader'.

Right now, I'm doing (first loader is babel in my case):
```js
module.exports.module.loaders[0].loaders.unshift('react-hot');
```

Is there a better way to do that in a non-hackish way?

**Comment by andywer** [comment]
Hey @eXon.

In v0.3.0 the `babel` block adds the babel loader in a post hook, so I think it should already work if you just use `devServer.reactHot()`.

**Comment by eXon** [comment]
Completely forgot about this one. I hate the GitHub search tool -.- thank!

**Comment by andywer** [comment]
No problem. But maybe the documentation should be improved if you as one of the main contributors forgot about it and could not find it 😉

**Comment by eXon** [comment]
I got a major issue with it though. The `react-hot` loader needs to be before `babel()` or the order will be wrong.

Right now `webpack-merge` is doing the merging and I can't decide if it is merged at the beginning or at the end of the array. Is there a better way to override it completely and give the full array with react-hot as the first loader and override it?

**Comment by andywer** [comment]
Hmm... I fear that this can only be solved by #34 :-/

**Comment by andywer** [comment]
Not yet. But I just wrote a [comment](https://github.com/andywer/webpack-blocks/issues/34#issuecomment-269522296) on which options I currently have in mind.

I thought about the same thing. Not sure if maybe something is wrong with your local setup (maybe outdated `@webpack-blocks/babel` version?). Maybe it's webpack-merge. I would look into webpack-merge if I had a little more time right now...

**Comment by pakokrew** [comment]
Hey, I agree that documentation must be improved on this part. 
Don't know if this is exactly the same problem, but I took a while to find that I had to put `import 'react-hot-loader/patch'` at the very begining of my app to make the HMR working. Could we just set something in the webpack config so that it adds `react-hot-loader/patch` as first entry point of the application ?

**Comment by andywer** [comment]
@pakokrew True 👍 Maybe we should provide a better solution as a separate HMR block. We could then add the `react-hot-loader` to the new block's dependencies.

**Comment by sapegin** [comment]
I’m for a separate block and better third-party so it would be maintained by someone who is actually using react-hot-loader. Since it’s not the only solution, and not even a recommended one.

**Comment by andywer** [comment]
Yeah, we should have a separate block for the hot loader. Not including it in the main repository / `webpack-blocks` package would hurt me a little bit inside, but basically it makes sense, since it's framework-specific.

Any other opinions?

**Comment by sapegin** [comment]
We’ve decided to deprecate React Hot Loader support, see more details in #209 and feel free to create (and share!) your own block.
