### ISSUE TITLE
For webpack2, remove json-loader

### ISSUE THREAD

**Issue by Tibfib** [andywer/webpack-blocks#63]
Per the docs, it's no longer necessary for webpack2: https://webpack.js.org/guides/migrating/#json-loader-is-not-required-anymore

**Comment by andywer** [comment]
Hey @Tibfib!

Fair enough. I read it, too, but didn't care so much for the moment, since it doesn't do any harm either.
But yes, dropping a dependency is probably a good thing :)

Feel free to open a PR or wait 'til someone else (probably me) does it, but without any guarantee when it's done.
