### ISSUE TITLE
Add simple testing to test-app

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#66]
I fear we will always have issues with the test-app unless there is some basic testing, even though the test app is no production code.

**Comment by tdeschryver** [comment]
Would it be enough to snapshot the config?
Or what do you have in mind?

**Comment by andywer** [comment]
Not sure yet, but snapshotting sounds reasonable...

**Comment by sapegin** [comment]
I would start from basic snapshots to at least know that it still does something ;-)

**Comment by andywer** [comment]
@tdeschryver Sure, go for it! 👍😊

**Comment by vlad-zhukov** [comment]
Looking at the code react-hot-loader isn't properly setup and most likely doesn't work.

**Comment by andywer** [comment]
@tdeschryver Did a good job to get started testing the test app, but in the future we should consider having an end-to-end test to check the build files.
