### ISSUE TITLE
Webpack 2 + PostCSS errors (Invalid configuration object ...)

### ISSUE THREAD

**Issue by dmitriz** [andywer/webpack-blocks#68]
I have tested `webpack.config.js` exactly as in 
https://github.com/andywer/webpack-blocks#usage
which lead to errors:

```bash
± |master ✓| → npm run build

> webpack2-blocks-test@0.1.0 build /Users/dmitrizaitsev/Dropbox/Sandbox/webpack2-blocks-test
> webpack

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           postcss: ...
         }
       })
     ]

npm ERR! Darwin 12.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/dmitrizaitsev/.npm-global/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! webpack2-blocks-test@0.1.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack2-blocks-test@0.1.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack2-blocks-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack2-blocks-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack2-blocks-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmitrizaitsev/Dropbox/Sandbox/webpack2-blocks-test/npm-debug.log

```

Here is the repo to reproduce the errors:

https://github.com/dmitriz/webpack-blocks-wp2-test

**Comment by andywer** [comment]
Ahh yeah. You cannot inline the PostCSS plugin configuration in your webpack config anymore when using webpack 2 🙈

We need to throw an error with a meaningful message in this case!

**Comment by dmitriz** [comment]
> Ahh yeah. You cannot inline the PostCSS plugin configuration in your webpack config anymore when using webpack 2 🙈

Are there convincing reasons for that (breaking ?) change?

**Comment by andywer** [comment]
The way the inlined PostCSS plugin config worked before was a little hacky (they added a `postcss` prop to the webpack config) and that doesn't work in webpack 2 anymore.

You cannot pass the PostCSS config via loader query parameters either, since the PostCSS config basically is JS code (incl. function calls and stuff) and thus cannot be serialized to JSON.

That's why they now want you to have separate file for the PostCSS config.

**Comment by dmitriz** [comment]
Can you not hide some meaningful default inside your block, so it just works?
Lots of folks will surely appreciate that.

**Comment by andywer** [comment]
Believe me, if I would know an easy solution I would have done it :)

I can ask @ai if he got an idea how we could configure PostCSS (the postcss-loader in fact) from within the webpack config (without a separate postcss config file).

**Comment by ai** [comment]
There is no way :) By some reason webpack 2 loose functions in loader `options`. This is why we force only PostCSS global config. But you can specify this config in `package.json`.

**Comment by dmitriz** [comment]
Sounds bad for the user :(

**Comment by ai** [comment]
@dmitriz if it is a problem for you. help us with `loader` options problem. You could investigate why it works in different way for different users.

**Comment by dmitriz** [comment]
That is above my competence I am afraid. I can help with functional programming and category theory though ;)

**Comment by andywer** [comment]
@ai Not sure if there can be a much better solution right now. I think the loader query params must be JSON-serializable which does not suite the PostCSS config. 90% sure...

**Comment by andywer** [comment]
I would take this issue and this line of thought and feed it back to the webpack usability discussion, but actually I am a bit fed up with their usability discussion right now and don't know if it would get much constructive feedback.

**Comment by dmitriz** [comment]
> I would take this issue and this line of thought and feed it back to the webpack usability discussion, but actually I am a bit fed up with their usability discussion right now and don't know if it would get much constructive feedback.

Sorry to hear, that sounds frustrating. 
Basically all they need to do is provide a hook or API
that you can use to make it simple for the user.

At least, wp 2 should not be harder than wp 1,
which itself can be made easier
(which I don't need to tell you :)

Here is an example what simple means:
https://github.com/mattdesl/budo

I can go to any directory and run 

```js
budo --live --open myfile.js 
```

and it will bundle it, run in the browser (without any html file!)
and even enable livereload.

What you are doing here, is really great
and will be, ironically, even more appreciated,
the harder the original tool becomes. 😈

**Comment by nightgrey** [comment]
I also had this issue and there are two underlying issues (webpack itself and postcss-loader) why the postcss block currently doesn't work with webpack 2. I already made a fork with a webpack 2 postcss block which I will create a pull request for in a few minutes.

**Comment by andywer** [comment]
Maybe we can still inline the PostCSS plugin config with webpack 2 by using the [Loader Options Plugin](https://webpack.js.org/guides/migrating/#loaderoptionsplugin-context) 🤔

@ai Have you already tried that?

**Comment by ai** [comment]
LoaderOptions plugin is a hack. It is just a temporary solution for migration process. Also having a separated PostCSS config is very great for PostCSS ecosystem.

One of the biggest PostCSS issue — hard to understand CSS on new project, because of different plugins. With one single config for all runner, new developers will understand used plugins faster. Same as `.babelrc` config.

Also one config could be used in many tools. Your IDE could take a config and highlight syntax according a plugins.

If you afraid about many configs in your root directory. Just put plugins lost in `package.json`.

**Comment by andywer** [comment]
@ai I know and I agree with you if it's a larger project. But if you just want to get a working webpack config with a basic PostCSS setup quickly it might be nice to be able to set everything from within the webpack config.

Another use case are presets: We could write a best-practices preset (#60) providing the PostCSS loader and a pre-configured autoprefixer if we would still be able to set the plugins from within the webpack config.

But sure, the LoaderOptionsPlugin is somewhat hacky, though...

**Comment by ai** [comment]
@andywer hm, presets is a good idea. I even think that end-users should not think about PostCSS plugins. They should think about features. Like `webpack-block-future-syntax` with Babel and cssnext. `webpack-blocks-linter` with ESLint and Stylelint. Or `webpack-blocks-css-isolation` with CSS Modules.

But in current webpack 2 we can’t pass a functions inside a PostCSS loader options :(.

How do you deal with `.babelrc` config?

**Comment by andywer** [comment]
Are you sure? I would have thought passing functions to the LoaderOptionsPlugin might work. Would be a shame if not...

Babel is easier, since its config is always JSON-serializable. We use loader query params for the Babel block.

**Comment by ai** [comment]
Yeap, `LoaderOptionsPlugin` works, but it is a temporary hack :).

I am not sure about anything in webpack, unfortunately :(.In all my cases functions works in PostCSS loader options. But I got many issue reports about problems with a functions from other webpack 2 users.

**Comment by andywer** [comment]
After sleeping a night about it:

@ai If you find some time maybe you can provide one or two links to the issues you talked about? Might help estimating the risk involved in going down that road.

I would be ok with using the `LoaderOptionsPlugin` for now if we don't have to fear any critical issues due to it. Presets will only be half the fun if you cannot ship a default PostCSS plugin config with them :)

**Comment by ai** [comment]
@andywer if I will add `config` option with a path to config file, will it help?

**Comment by andywer** [comment]
@ai I fear it will not. I think an elegant solution should work with a config set from within the webpack config, but allow you to opt-in for a separate `postcss.config.js`.

**Comment by ai** [comment]
@andywer sure, I will accept any fix that you will send to me. I just gave up with all non-consistent maginc inside webpack :(.

Technically, `postcss-loader` supports options via webpack 2 new syntax: https://github.com/postcss/postcss-loader/blob/master/index.js#L48

Use it on your own risk.

**Comment by ai** [comment]
@andywer `postcss-loader` now supports `plugins` parameter officially https://github.com/postcss/postcss-loader#plugins

**Comment by andywer** [comment]
@ai Cool! Will check it out :)

**Comment by andywer** [comment]
@ai Tried it, but does not work either. We are still using the webpack-1.x-style `module.loaders` config (not the webpack 2 `rules`). Using both styles is a terrible idea as well, since it's not only hacky, but messes up the config merging :-/

I even thought about switching the webpack-2-style `rules` syntax by default and just adding a compatibility layer for webpack 1 (turning any `rules` into `module.loaders`). But this is tricky as well, since the new `rules` syntax is a little more powerful. Thus there might be `rules` that cannot be converted to `module.loaders` at all...

**Comment by andywer** [comment]
I stand corrected: Building an abstraction layer `rules => module.loaders` for webpack 1 should be easy as long as the options passed to the loaders are JSON-serializable (can just turn them into JSON query string) 😉

**Comment by ai** [comment]
@andywer in this case I think you can still use `LoaderOptionsPlugin` until you will drop webpack 1 support or find some better idea to fix it. Hacks is OK for temporary solutions.

**Comment by andywer** [comment]
@ai 👍👍
@dmitriz The `LoaderOptionsPlugin` fix works. Will ship it very soon.

Stay tuned! 📻😉

**Comment by andywer** [comment]
And again... Sorry for the inconvenience, guys!
