### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#7]
# Current situation

webpack-blocks makes writing easy-to-maintain webpack configurations simpler. But it is still not trivial for a newbie to set up a webpack config in the first place.

You have to install multiple webpack-block packages and still need to be aware of which blocks you need and what the best practices are (like using `DefinePlugin` to set `process.env` to `production` when using React).

# Ideas to improve things

* Bundle most common webpack blocks together in one npm package (like Babel, Dev server, PostCSS)
* Provide *best practice settings & plugins* out of the box easily (like `@webpack-blocks/react-preset`)
* CLI tool to install packages and set up `package.json` `scripts` (loosely based on #1)

Additional considerations:
* Potential CLI tool could allow different source code templates to be used (React vs Angular 2, Redux vs Mobx vs RxJs, CSS vs Styled components)

**Comment by andywer** [comment]
Prior art:
There is https://github.com/webpack-preset/webpack-preset by @timdorr. I like the basic idea, but as it says it *is for quick prototyping and should not be used long-term in your projects*.

Maybe we can do better leveraging the modular & composable nature of webpack-blocks.

The biggest problem might be the scenario of two presets being used together that ship conflicting configuration blocks. But maybe it's ok to allow using only one preset, plus a set of additional feature blocks you choose yourself.

**Comment by eXon** [comment]
I think we can already do presets with `webpack-blocks`. All we actually need to do is a concat on the array before `createConfig`.

What if `webpack-blocks` was providing a few useful presets? I could already do a `benoit-blocks` with my own presets like this:

```js
const benoitConfig = require('benoit-config');

module.exports = createConfig(benoitConfig.concat([
  // ...
]))
```

This is so simple I don't think we even need an `exends` method.

Anybody could share their own defaults and webpack-blocks could provide a few ones.

What's your though on that?

**Comment by andywer** [comment]
The approach I have in mind is based on [env()](https://github.com/andywer/webpack-blocks/tree/master/packages/core#envenvname-string-configsetters-function-function). You know, that helper to apply some blocks only in `development` or `production`.

This tiny helper basically aggregates multiple blocks to one. This is the basically the very same thing as a preset :)

But yeah, it really is that simple.

**Comment by andywer** [comment]
@eXon I created a new issue for the preset feature: #24. It also incorporates existing thoughts on the topic. Feel free to provide feedback :)

**Comment by andywer** [comment]
Those were early ideas of mine. Do you still think they are relevant?

I'd focus on our main 1.0 features for now.
Suggestion: Remove from 1.0 milestone.

@sapegin?

**Comment by sapegin** [comment]
> Bundle most common webpack blocks together in one npm package (like Babel, Dev server, PostCSS)

This is done already.

> Provide best practice settings & plugins out of the box easily (like @webpack-blocks/react-preset)

I’m not that sure that presets are a good idea because to change something you’ll need to rewrite your config without a preset, so a cookbook would be a more maintainable solution I think.

> CLI tool to install packages and set up package.json scripts (loosely based on #1)

Let’s use [Mrm](https://github.com/sapegin/mrm) for that ;-)

**Comment by dmitmel** [comment]
@andywer This issue is really old and outdated. Should it be closed?

**Comment by andywer** [comment]
Yeah, let's close it for now 👍
