### ISSUE TITLE
Question: why use Object.assign rather than just setting hook properties on the fn?

### ISSUE THREAD

**Issue by jeffbski** [andywer/webpack-blocks#72]
In reading the docs for block creation, I was wondering if there was a reason why you use Object.assign rather than just setting the properties on the function directly? 

I'm not trying to nitpick here, only trying to make sure I'm not missing something since it seems that the result would be the same.

So the existing docs give this example using Object.assign:

```js
function myBlock () {
  const blockFunction = (context, config) => ({ /* webpack config snippet */ })

  return Object.assign(blockFunction, {
    pre: preHook,
    post: postHook
  })
}

function preHook (context) {
  // Manipulate the `context` here (register a new file type, for example)
}

function postHook (context, config) {
  return { /* webpack config snippet */ }
}
```

And it seems to me that the equivalent code is simply to set the properties on the function directly.

```js
function myBlock () {
  const blockFunction = (context, config) => ({ /* webpack config snippet */ })
  blockFunction.pre = preHook;
  blockFunction.post = postHook;
  return blockFunction;
}

function preHook (context) {
  // Manipulate the `context` here (register a new file type, for example)
}

function postHook (context, config) {
  return { /* webpack config snippet */ }
}
```

Is there any technical reason that you are recommending using Object.assign or would it be just the same to set the properties directly?

Thanks!

**Comment by andywer** [comment]
Hey @jeffbski!

No, it's really just a random code style decision and is semantically equivalent. But it might make sense to explicitly point that out somewhere in the docs, though :)

**Comment by jeffbski** [comment]
Excellent. I just wanted to make sure I wasn't missing something important there.
