### ISSUE TITLE
defineConstants is evaluated build-time and may lead to bugs on different environment

### ISSUE THREAD

**Issue by sdwvit** [andywer/webpack-blocks#75]
Imagine you deploy your application on different targets, eg amazon, local, remote server, etc. You pass some links environment vars with service addresses. You expect to have binding. Instead you have webpack replace all process.env notation with constant value - not reference. 
This way defineConstants is capable only for providing environment constants of machine the bundle was built on. Having this bundle deployed on different environment makes no sense, as all constants are not reevaluated and lead to breakage of app.
I do suggest to add comment on this somewhere in docs as it may lead to confusion.

**Comment by andywer** [comment]
Hey @sdwvit.

I didn't recognize that this behavior might cause confusion. Do you think it's enough to document it in the `webpack`/`webpack2` package's README or should I add it to the FAQ ("You might want to know" at the bottom of the main README) as well?

**Comment by sdwvit** [comment]
Hey @andywer thanks for quick response. Yeah, I think webpack's repo is better place for this one.

**Comment by andywer** [comment]
@sdwvit That's not even what I meant 😅

I meant https://github.com/andywer/webpack-blocks/tree/master/packages/webpack and https://github.com/andywer/webpack-blocks/tree/master/packages/webpack2. And possibly webpack-blocks main README 😉

**Comment by sdwvit** [comment]
Oh, sorry. Yes, any place you mentioned is good.

**Comment by andywer** [comment]
Just updated the [README](https://github.com/andywer/webpack-blocks#you-might-want-to-know) 😊

Would you have found it there when you were wondering about `defineConstants()`?
