### ISSUE TITLE
Document how to deal with new MIME types

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#87]
There are two ways to handle this:

1. Just add them to the default types. Easy, but requires a new `@webpack-blocks/core` release and won't work with any previous `@webpack-blocks/core` version.
2. Have a `pre` hook that does `context.fileTypes.add()`. No new release of `@webpack-block/core` necessary.
3. (both: 2., but still add it to the default types like 1.)

## Not completely sorted out yet

- What is the suggested way of doing that (see options above)?

## To Do

- Improve documentation ("How to write a block")

**Comment by SuperManitu** [comment]
I would suggest to use 3, because standard file extensions should be in the default file (like typescript, less, everything "common"). But for some projects you might have other files you want to include, so the easiest way to do it is to write a custom block using the pre hook.

**Comment by SuperManitu** [comment]
Another benefit is that new blocks supporting new file types do not need to depend on a new version of the core, they can add it in a prehook if it's not defined

**Comment by andywer** [comment]
Sure. We should make `2.` (pre hook) mandatory if a new file type is introduced and additionally opt-in for `1.` (add it to default types) if the type is widely used 👍
