### ISSUE TITLE
Defining multiple entry points

### ISSUE THREAD

**Issue by booleanhunter** [andywer/webpack-blocks#89]
I wish to divide my JS codes into mulltiple bundles, by specifying multiple entry points and output file names. I'd also like to know how to define aliases while including node/bower modules and libraries.

Is there a way to do it using webpack-blocks?

Example [webpack.config.js](https://github.com/booleanhunter/ReactJS-AdminLTE/blob/master/webpack.config.js) file

**Comment by eXon** [comment]
`entry` -> `entryPoint()`
`output` -> `setOutput()`
`resolve.alias` -> `resolveAliases()`

They are all from `@webpack-blocks/webpack`

**Comment by eXon** [comment]
@andywer Might be a good idea to document all those

**Comment by andywer** [comment]
@eXon Yep, right. Right now there is just the list of functions in the `webpack`/`webpack2` [README](https://github.com/andywer/webpack-blocks/tree/master/packages/webpack#addpluginsplugins-webpackplugin) and the rest is [documented in the code](https://github.com/andywer/webpack-blocks/blob/master/packages/webpack-common/src/webpack.js) only. Need to complete the READMEs soon.

Created an issue for that: #90

@booleanhunter Is the information we provided here enough for you to handle your use case?

**Comment by booleanhunter** [comment]
@eXon @andywer Thank you for the prompt response!

So what I would like to know is, would I be able to use `entryPoint()` multiple times, and specify the bundle output file names for each of the entry points? Say for example I had two entry points `widgets.js` and `dashboard.js`. I would like to have two separate output bundles named as `widgets.bundle.js` and `dashboard.bundle.js`. 

Additionally, I would like to have a separate bundle `vendors.bundle.js`, which would contain all vendors like JQuery, React, Bootstrap, D3.js etc. How can I do that using webpack-blocks?

**Comment by andywer** [comment]
@booleanhunter Having multiple `entryPoint()` should work. Try it like this: `entryPoint({ dashboard: 'path/to/dashboard/source', widget: 'path/to/widget/source', vendor: [ 'jquery', 'react' ] })`. You can then specify where to write the bundle files using `setOutput()` or omit it and just stick to the default.

Basically it works pretty much the same as it always did for webpack: https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code

@eXon Thank you for helping so quickly :)

**Comment by booleanhunter** [comment]
This is indeed helpful. Once again thank you @andywer @eXon . This is great work!
