### ISSUE TITLE
Add testing/setup documentation for contributors

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#91]
## Package linking / testing before publishing

- `lerna bootstrap`
- Point out that `lerna bootstrap` is run automatically on `postinstall` (on Travis CI, too)
- `npm link`

## Testing concept

Types of tests:
- Unit tests
- Integration tests
- End-to-end tests

(What they reside, where they occur and when to write which one(s))

## Common pitfalls

- e2e tests: Copy `dependencies` of blocks to test into the `devDependencies` of `webpack`/`webpack2`

**Comment by sapegin** [comment]
We could close this soon :-) 

* Package linking / testing before publishing — will be done in #185
* Testing concept — done already
* Common pitfalls — not sure about that

**Comment by sapegin** [comment]
> Common pitfalls — not sure about that

What can we do to solve this?

**Comment by andywer** [comment]
Yeah, let's close it for now 😉
